# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       libXxf86misc
Summary:    X.Org X11 libXxf86misc runtime library
Version:    1.0.3
Release:    0
Group:      System/Libraries
License:    MIT/X11
URL:        http://www.x.org
Source0:    ftp://ftp.x.org/pub/individual/lib/%{name}-%{version}.tar.bz2
Source100:  libXxf86misc.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(xext)
BuildRequires:  pkgconfig(xproto)
BuildRequires:  pkgconfig(xextproto)
BuildRequires:  pkgconfig(xf86miscproto)


%description
Extension library for the XFree86-Misc X extension.


%package devel
Summary:    X.Org X11 libXxf86misc development package
Group:      System/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Extension development library for the XFree86-Misc X extension.



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files
%defattr(-,root,root,-)
# >> files
# FIXME: Missing some of the doc files %doc AUTHORS COPYING README INSTALL ChangeLog
#%doc COPYING ChangeLog
%{_libdir}/libXxf86misc.so.1
%{_libdir}/libXxf86misc.so.1.1.0
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_libdir}/libXxf86misc.so
%{_libdir}/pkgconfig/xxf86misc.pc
%dir %{_mandir}/man3
%doc %{_mandir}/man3/*

# << files devel

